possible: possible.c
	gcc -ggdb -o possible possible.c 

minimum: minimum.c
	gcc -ggdb -o minimum minimum.c

one: possible
	./possible input.txt -r 12 -g 13 -b 14 -p -s

two: minimum
	./minimum input.txt -p -s 
